// Code generated by qtc from "metrics_response.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vtselect/traces/tempo/metrics_response.qtpl:1
package tempo

//line app/vtselect/traces/tempo/metrics_response.qtpl:1
import (
	"strconv"
)

//line app/vtselect/traces/tempo/metrics_response.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vtselect/traces/tempo/metrics_response.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vtselect/traces/tempo/metrics_response.qtpl:7
func StreamMetricsQueryRangeResponse(qw422016 *qt422016.Writer, series []tempoMetricsSeries) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:7
	qw422016.N().S(`{"series":[`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:10
	if len(series) > 0 {
//line app/vtselect/traces/tempo/metrics_response.qtpl:11
		streammetricsSeriesJson(qw422016, &series[0])
//line app/vtselect/traces/tempo/metrics_response.qtpl:12
		for i := 1; i < len(series); i++ {
//line app/vtselect/traces/tempo/metrics_response.qtpl:12
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:13
			streammetricsSeriesJson(qw422016, &series[i])
//line app/vtselect/traces/tempo/metrics_response.qtpl:14
		}
//line app/vtselect/traces/tempo/metrics_response.qtpl:15
	}
//line app/vtselect/traces/tempo/metrics_response.qtpl:15
	qw422016.N().S(`],"metrics":{"inspectedBytes":"0","inspectedTraces":0,"totalJobs":0,"completedJobs":0},"status":"COMPLETE"}`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:25
func WriteMetricsQueryRangeResponse(qq422016 qtio422016.Writer, series []tempoMetricsSeries) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	StreamMetricsQueryRangeResponse(qw422016, series)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:25
func MetricsQueryRangeResponse(series []tempoMetricsSeries) string {
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	WriteMetricsQueryRangeResponse(qb422016, series)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	return qs422016
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:27
func streammetricsSeriesJson(qw422016 *qt422016.Writer, s *tempoMetricsSeries) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:27
	qw422016.N().S(`{"labels":[`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:30
	if len(s.Labels) > 0 {
//line app/vtselect/traces/tempo/metrics_response.qtpl:31
		streammetricsLabelJson(qw422016, &s.Labels[0])
//line app/vtselect/traces/tempo/metrics_response.qtpl:32
		for i := 1; i < len(s.Labels); i++ {
//line app/vtselect/traces/tempo/metrics_response.qtpl:32
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:33
			streammetricsLabelJson(qw422016, &s.Labels[i])
//line app/vtselect/traces/tempo/metrics_response.qtpl:34
		}
//line app/vtselect/traces/tempo/metrics_response.qtpl:35
	}
//line app/vtselect/traces/tempo/metrics_response.qtpl:35
	qw422016.N().S(`],"samples":[`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:38
	if len(s.Samples) > 0 {
//line app/vtselect/traces/tempo/metrics_response.qtpl:39
		streammetricsSampleJson(qw422016, &s.Samples[0])
//line app/vtselect/traces/tempo/metrics_response.qtpl:40
		for i := 1; i < len(s.Samples); i++ {
//line app/vtselect/traces/tempo/metrics_response.qtpl:40
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:41
			streammetricsSampleJson(qw422016, &s.Samples[i])
//line app/vtselect/traces/tempo/metrics_response.qtpl:42
		}
//line app/vtselect/traces/tempo/metrics_response.qtpl:43
	}
//line app/vtselect/traces/tempo/metrics_response.qtpl:43
	qw422016.N().S(`],"exemplars":[]}`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:47
func writemetricsSeriesJson(qq422016 qtio422016.Writer, s *tempoMetricsSeries) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
	streammetricsSeriesJson(qw422016, s)
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:47
func metricsSeriesJson(s *tempoMetricsSeries) string {
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
	writemetricsSeriesJson(qb422016, s)
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
	return qs422016
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:49
func streammetricsLabelJson(qw422016 *qt422016.Writer, l *tempoLabel) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:49
	qw422016.N().S(`{"key":`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:51
	qw422016.N().Q(l.Key)
//line app/vtselect/traces/tempo/metrics_response.qtpl:51
	qw422016.N().S(`,"value":{"stringValue":`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:53
	qw422016.N().Q(l.Value)
//line app/vtselect/traces/tempo/metrics_response.qtpl:53
	qw422016.N().S(`}}`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:56
func writemetricsLabelJson(qq422016 qtio422016.Writer, l *tempoLabel) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
	streammetricsLabelJson(qw422016, l)
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:56
func metricsLabelJson(l *tempoLabel) string {
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
	writemetricsLabelJson(qb422016, l)
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
	return qs422016
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:58
func streammetricsSampleJson(qw422016 *qt422016.Writer, s *tempoSample) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:58
	qw422016.N().S(`{"timestampMs":"`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:60
	qw422016.N().S(strconv.FormatInt(s.TimestampMs, 10))
//line app/vtselect/traces/tempo/metrics_response.qtpl:60
	qw422016.N().S(`","value":`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:61
	qw422016.N().F(s.Value)
//line app/vtselect/traces/tempo/metrics_response.qtpl:61
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:63
func writemetricsSampleJson(qq422016 qtio422016.Writer, s *tempoSample) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
	streammetricsSampleJson(qw422016, s)
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:63
func metricsSampleJson(s *tempoSample) string {
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
	writemetricsSampleJson(qb422016, s)
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
	return qs422016
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
}
