// Code generated by qtc from "tempo.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vtselect/traces/tempo/tempo.qtpl:1
package tempo

//line app/vtselect/traces/tempo/tempo.qtpl:1
import (
	"sort"
)

//line app/vtselect/traces/tempo/tempo.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vtselect/traces/tempo/tempo.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vtselect/traces/tempo/tempo.qtpl:7
func StreamSearchTagsResponse(qw422016 *qt422016.Writer, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:7
	qw422016.N().S(`{`)
//line app/vtselect/traces/tempo/tempo.qtpl:10
	sort.Slice(resourceTagList, func(i, j int) bool { return resourceTagList[i] < resourceTagList[j] })
	sort.Slice(spanTagList, func(i, j int) bool { return spanTagList[i] < spanTagList[j] })
	sort.Slice(eventTagList, func(i, j int) bool { return eventTagList[i] < eventTagList[j] })
	sort.Slice(linkTagList, func(i, j int) bool { return linkTagList[i] < linkTagList[j] })
	sort.Slice(instrumentationScopeTagList, func(i, j int) bool { return instrumentationScopeTagList[i] < instrumentationScopeTagList[j] })

//line app/vtselect/traces/tempo/tempo.qtpl:15
	qw422016.N().S(`"scopes":[{"name": "resource","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:20
	if len(resourceTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:21
		qw422016.N().Q(resourceTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:22
		for _, tag := range resourceTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:22
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:23
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:24
		}
//line app/vtselect/traces/tempo/tempo.qtpl:25
	}
//line app/vtselect/traces/tempo/tempo.qtpl:25
	qw422016.N().S(`]},{"name": "span","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:31
	if len(spanTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:32
		qw422016.N().Q(spanTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:33
		for _, tag := range spanTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:33
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:34
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:35
		}
//line app/vtselect/traces/tempo/tempo.qtpl:36
	}
//line app/vtselect/traces/tempo/tempo.qtpl:36
	qw422016.N().S(`]},{"name": "event","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:42
	if len(eventTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:43
		qw422016.N().Q(eventTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:44
		for _, tag := range eventTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:44
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:45
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:46
		}
//line app/vtselect/traces/tempo/tempo.qtpl:47
	}
//line app/vtselect/traces/tempo/tempo.qtpl:47
	qw422016.N().S(`]},{"name": "link","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:53
	if len(linkTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:54
		qw422016.N().Q(linkTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:55
		for _, tag := range linkTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:55
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:56
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:57
		}
//line app/vtselect/traces/tempo/tempo.qtpl:58
	}
//line app/vtselect/traces/tempo/tempo.qtpl:58
	qw422016.N().S(`]},{"name": "instrumentation","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:64
	if len(instrumentationScopeTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:65
		qw422016.N().Q(instrumentationScopeTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:66
		for _, tag := range instrumentationScopeTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:66
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:67
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:68
		}
//line app/vtselect/traces/tempo/tempo.qtpl:69
	}
//line app/vtselect/traces/tempo/tempo.qtpl:69
	qw422016.N().S(`]}],"metrics": {"inspectedBytes": "0"}}`)
//line app/vtselect/traces/tempo/tempo.qtpl:77
}

//line app/vtselect/traces/tempo/tempo.qtpl:77
func WriteSearchTagsResponse(qq422016 qtio422016.Writer, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:77
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tempo.qtpl:77
	StreamSearchTagsResponse(qw422016, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList)
//line app/vtselect/traces/tempo/tempo.qtpl:77
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tempo.qtpl:77
}

//line app/vtselect/traces/tempo/tempo.qtpl:77
func SearchTagsResponse(resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList []string) string {
//line app/vtselect/traces/tempo/tempo.qtpl:77
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tempo.qtpl:77
	WriteSearchTagsResponse(qb422016, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList)
//line app/vtselect/traces/tempo/tempo.qtpl:77
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tempo.qtpl:77
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tempo.qtpl:77
	return qs422016
//line app/vtselect/traces/tempo/tempo.qtpl:77
}

//line app/vtselect/traces/tempo/tempo.qtpl:79
func StreamSearchTagValuesResponse(qw422016 *qt422016.Writer, tagValueList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:79
	qw422016.N().S(`{`)
//line app/vtselect/traces/tempo/tempo.qtpl:82
	sort.Slice(tagValueList, func(i, j int) bool { return tagValueList[i] < tagValueList[j] })

//line app/vtselect/traces/tempo/tempo.qtpl:83
	qw422016.N().S(`"tagValues":[`)
//line app/vtselect/traces/tempo/tempo.qtpl:85
	if len(tagValueList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:85
		qw422016.N().S(`{"type": "string","value":`)
//line app/vtselect/traces/tempo/tempo.qtpl:88
		qw422016.N().Q(tagValueList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:88
		qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tempo.qtpl:90
	}
//line app/vtselect/traces/tempo/tempo.qtpl:91
	if len(tagValueList) > 1 {
//line app/vtselect/traces/tempo/tempo.qtpl:92
		for _, tag := range tagValueList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:92
			qw422016.N().S(`,{"type": "string","value":`)
//line app/vtselect/traces/tempo/tempo.qtpl:95
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:95
			qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tempo.qtpl:97
		}
//line app/vtselect/traces/tempo/tempo.qtpl:98
	}
//line app/vtselect/traces/tempo/tempo.qtpl:98
	qw422016.N().S(`],"metrics": {"inspectedBytes": "0"}}`)
//line app/vtselect/traces/tempo/tempo.qtpl:104
}

//line app/vtselect/traces/tempo/tempo.qtpl:104
func WriteSearchTagValuesResponse(qq422016 qtio422016.Writer, tagValueList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:104
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tempo.qtpl:104
	StreamSearchTagValuesResponse(qw422016, tagValueList)
//line app/vtselect/traces/tempo/tempo.qtpl:104
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tempo.qtpl:104
}

//line app/vtselect/traces/tempo/tempo.qtpl:104
func SearchTagValuesResponse(tagValueList []string) string {
//line app/vtselect/traces/tempo/tempo.qtpl:104
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tempo.qtpl:104
	WriteSearchTagValuesResponse(qb422016, tagValueList)
//line app/vtselect/traces/tempo/tempo.qtpl:104
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tempo.qtpl:104
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tempo.qtpl:104
	return qs422016
//line app/vtselect/traces/tempo/tempo.qtpl:104
}

//line app/vtselect/traces/tempo/tempo.qtpl:106
func StreamSearchResponse(qw422016 *qt422016.Writer, summaryList []traceSummary) {
//line app/vtselect/traces/tempo/tempo.qtpl:106
	qw422016.N().S(`{"traces": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:109
	if len(summaryList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:110
		streamsummaryJson(qw422016, summaryList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:111
		for _, summary := range summaryList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:111
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:112
			streamsummaryJson(qw422016, summary)
//line app/vtselect/traces/tempo/tempo.qtpl:113
		}
//line app/vtselect/traces/tempo/tempo.qtpl:114
	}
//line app/vtselect/traces/tempo/tempo.qtpl:114
	qw422016.N().S(`]}`)
//line app/vtselect/traces/tempo/tempo.qtpl:117
}

//line app/vtselect/traces/tempo/tempo.qtpl:117
func WriteSearchResponse(qq422016 qtio422016.Writer, summaryList []traceSummary) {
//line app/vtselect/traces/tempo/tempo.qtpl:117
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tempo.qtpl:117
	StreamSearchResponse(qw422016, summaryList)
//line app/vtselect/traces/tempo/tempo.qtpl:117
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tempo.qtpl:117
}

//line app/vtselect/traces/tempo/tempo.qtpl:117
func SearchResponse(summaryList []traceSummary) string {
//line app/vtselect/traces/tempo/tempo.qtpl:117
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tempo.qtpl:117
	WriteSearchResponse(qb422016, summaryList)
//line app/vtselect/traces/tempo/tempo.qtpl:117
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tempo.qtpl:117
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tempo.qtpl:117
	return qs422016
//line app/vtselect/traces/tempo/tempo.qtpl:117
}

//line app/vtselect/traces/tempo/tempo.qtpl:119
func streamsummaryJson(qw422016 *qt422016.Writer, summary traceSummary) {
//line app/vtselect/traces/tempo/tempo.qtpl:119
	qw422016.N().S(`{"traceID":`)
//line app/vtselect/traces/tempo/tempo.qtpl:121
	qw422016.N().Q(summary.traceID)
//line app/vtselect/traces/tempo/tempo.qtpl:121
	qw422016.N().S(`,"rootServiceName":`)
//line app/vtselect/traces/tempo/tempo.qtpl:122
	qw422016.N().Q(summary.rootServiceName)
//line app/vtselect/traces/tempo/tempo.qtpl:122
	qw422016.N().S(`,"rootTraceName":`)
//line app/vtselect/traces/tempo/tempo.qtpl:123
	qw422016.N().Q(summary.rootTraceName)
//line app/vtselect/traces/tempo/tempo.qtpl:123
	qw422016.N().S(`,"startTimeUnixNano":"`)
//line app/vtselect/traces/tempo/tempo.qtpl:124
	qw422016.N().DL(summary.startTimeUnixNano)
//line app/vtselect/traces/tempo/tempo.qtpl:124
	qw422016.N().S(`","durationMs":`)
//line app/vtselect/traces/tempo/tempo.qtpl:125
	qw422016.N().DL((summary.endTimeUnixNano - summary.startTimeUnixNano) / 1e6)
//line app/vtselect/traces/tempo/tempo.qtpl:125
	qw422016.N().S(`,"spanSets": []}`)
//line app/vtselect/traces/tempo/tempo.qtpl:128
}

//line app/vtselect/traces/tempo/tempo.qtpl:128
func writesummaryJson(qq422016 qtio422016.Writer, summary traceSummary) {
//line app/vtselect/traces/tempo/tempo.qtpl:128
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tempo.qtpl:128
	streamsummaryJson(qw422016, summary)
//line app/vtselect/traces/tempo/tempo.qtpl:128
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tempo.qtpl:128
}

//line app/vtselect/traces/tempo/tempo.qtpl:128
func summaryJson(summary traceSummary) string {
//line app/vtselect/traces/tempo/tempo.qtpl:128
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tempo.qtpl:128
	writesummaryJson(qb422016, summary)
//line app/vtselect/traces/tempo/tempo.qtpl:128
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tempo.qtpl:128
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tempo.qtpl:128
	return qs422016
//line app/vtselect/traces/tempo/tempo.qtpl:128
}
