// Code generated by qtc from "tracebyid.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vtselect/traces/tempo/tracebyid.qtpl:1
package tempo

//line app/vtselect/traces/tempo/tracebyid.qtpl:1
import (
	"strconv"

	otelpb "github.com/VictoriaMetrics/VictoriaTraces/lib/protoparser/opentelemetry/pb"
)

//line app/vtselect/traces/tempo/tracebyid.qtpl:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vtselect/traces/tempo/tracebyid.qtpl:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vtselect/traces/tempo/tracebyid.qtpl:13
func StreamTraceByIDV1JSON(qw422016 *qt422016.Writer, resourceSpans []*otelpb.ResourceSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:13
	qw422016.N().S(`{"batches":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:15
	streamresourceSpansArrayJSON(qw422016, resourceSpans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:15
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:17
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:17
func WriteTraceByIDV1JSON(qq422016 qtio422016.Writer, resourceSpans []*otelpb.ResourceSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:17
	StreamTraceByIDV1JSON(qw422016, resourceSpans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:17
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:17
func TraceByIDV1JSON(resourceSpans []*otelpb.ResourceSpans) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:17
	WriteTraceByIDV1JSON(qb422016, resourceSpans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:17
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:17
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:17
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:23
func StreamTraceByIDV2JSON(qw422016 *qt422016.Writer, resourceSpans []*otelpb.ResourceSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:23
	qw422016.N().S(`{"trace":{"resourceSpans":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:26
	streamresourceSpansArrayJSON(qw422016, resourceSpans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:26
	qw422016.N().S(`},"metrics":{"inspectedBytes":"0"}}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:32
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:32
func WriteTraceByIDV2JSON(qq422016 qtio422016.Writer, resourceSpans []*otelpb.ResourceSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:32
	StreamTraceByIDV2JSON(qw422016, resourceSpans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:32
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:32
func TraceByIDV2JSON(resourceSpans []*otelpb.ResourceSpans) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:32
	WriteTraceByIDV2JSON(qb422016, resourceSpans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:32
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:32
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:32
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:34
func streamresourceSpansArrayJSON(qw422016 *qt422016.Writer, resourceSpans []*otelpb.ResourceSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:34
	qw422016.N().S(`[`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:36
	if len(resourceSpans) > 0 {
//line app/vtselect/traces/tempo/tracebyid.qtpl:37
		streamresourceSpansJSON(qw422016, resourceSpans[0])
//line app/vtselect/traces/tempo/tracebyid.qtpl:38
		for _, rs := range resourceSpans[1:] {
//line app/vtselect/traces/tempo/tracebyid.qtpl:38
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:39
			streamresourceSpansJSON(qw422016, rs)
//line app/vtselect/traces/tempo/tracebyid.qtpl:40
		}
//line app/vtselect/traces/tempo/tracebyid.qtpl:41
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:41
	qw422016.N().S(`]`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:43
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:43
func writeresourceSpansArrayJSON(qq422016 qtio422016.Writer, resourceSpans []*otelpb.ResourceSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:43
	streamresourceSpansArrayJSON(qw422016, resourceSpans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:43
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:43
func resourceSpansArrayJSON(resourceSpans []*otelpb.ResourceSpans) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:43
	writeresourceSpansArrayJSON(qb422016, resourceSpans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:43
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:43
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:43
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:45
func streamresourceSpansJSON(qw422016 *qt422016.Writer, rs *otelpb.ResourceSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:45
	qw422016.N().S(`{"resource":{"attributes":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:48
	streamkeyValueListJSON(qw422016, rs.Resource.Attributes)
//line app/vtselect/traces/tempo/tracebyid.qtpl:48
	qw422016.N().S(`},"scopeSpans":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:50
	streamscopeSpansArrayJSON(qw422016, rs.ScopeSpans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:50
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:52
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:52
func writeresourceSpansJSON(qq422016 qtio422016.Writer, rs *otelpb.ResourceSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:52
	streamresourceSpansJSON(qw422016, rs)
//line app/vtselect/traces/tempo/tracebyid.qtpl:52
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:52
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:52
func resourceSpansJSON(rs *otelpb.ResourceSpans) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:52
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:52
	writeresourceSpansJSON(qb422016, rs)
//line app/vtselect/traces/tempo/tracebyid.qtpl:52
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:52
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:52
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:52
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:54
func streamscopeSpansArrayJSON(qw422016 *qt422016.Writer, scopeSpans []*otelpb.ScopeSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:54
	qw422016.N().S(`[`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:56
	if len(scopeSpans) > 0 {
//line app/vtselect/traces/tempo/tracebyid.qtpl:57
		streamscopeSpansJSON(qw422016, scopeSpans[0])
//line app/vtselect/traces/tempo/tracebyid.qtpl:58
		for _, ss := range scopeSpans[1:] {
//line app/vtselect/traces/tempo/tracebyid.qtpl:58
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:59
			streamscopeSpansJSON(qw422016, ss)
//line app/vtselect/traces/tempo/tracebyid.qtpl:60
		}
//line app/vtselect/traces/tempo/tracebyid.qtpl:61
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:61
	qw422016.N().S(`]`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:63
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:63
func writescopeSpansArrayJSON(qq422016 qtio422016.Writer, scopeSpans []*otelpb.ScopeSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:63
	streamscopeSpansArrayJSON(qw422016, scopeSpans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:63
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:63
func scopeSpansArrayJSON(scopeSpans []*otelpb.ScopeSpans) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:63
	writescopeSpansArrayJSON(qb422016, scopeSpans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:63
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:63
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:63
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:65
func streamscopeSpansJSON(qw422016 *qt422016.Writer, ss *otelpb.ScopeSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:65
	qw422016.N().S(`{"scope":{"name":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:68
	qw422016.N().Q(ss.Scope.Name)
//line app/vtselect/traces/tempo/tracebyid.qtpl:68
	qw422016.N().S(`,"version":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:69
	qw422016.N().Q(ss.Scope.Version)
//line app/vtselect/traces/tempo/tracebyid.qtpl:69
	qw422016.N().S(`,"attributes":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:70
	streamkeyValueListJSON(qw422016, ss.Scope.Attributes)
//line app/vtselect/traces/tempo/tracebyid.qtpl:70
	qw422016.N().S(`},"spans":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:72
	streamspansArrayJSON(qw422016, ss.Spans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:72
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:74
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:74
func writescopeSpansJSON(qq422016 qtio422016.Writer, ss *otelpb.ScopeSpans) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:74
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:74
	streamscopeSpansJSON(qw422016, ss)
//line app/vtselect/traces/tempo/tracebyid.qtpl:74
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:74
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:74
func scopeSpansJSON(ss *otelpb.ScopeSpans) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:74
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:74
	writescopeSpansJSON(qb422016, ss)
//line app/vtselect/traces/tempo/tracebyid.qtpl:74
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:74
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:74
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:74
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:76
func streamspansArrayJSON(qw422016 *qt422016.Writer, spans []*otelpb.Span) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:76
	qw422016.N().S(`[`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:78
	if len(spans) > 0 {
//line app/vtselect/traces/tempo/tracebyid.qtpl:79
		streamspanJSON(qw422016, spans[0])
//line app/vtselect/traces/tempo/tracebyid.qtpl:80
		for _, s := range spans[1:] {
//line app/vtselect/traces/tempo/tracebyid.qtpl:80
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:81
			streamspanJSON(qw422016, s)
//line app/vtselect/traces/tempo/tracebyid.qtpl:82
		}
//line app/vtselect/traces/tempo/tracebyid.qtpl:83
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:83
	qw422016.N().S(`]`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:85
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:85
func writespansArrayJSON(qq422016 qtio422016.Writer, spans []*otelpb.Span) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:85
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:85
	streamspansArrayJSON(qw422016, spans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:85
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:85
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:85
func spansArrayJSON(spans []*otelpb.Span) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:85
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:85
	writespansArrayJSON(qb422016, spans)
//line app/vtselect/traces/tempo/tracebyid.qtpl:85
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:85
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:85
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:85
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:87
func streamspanJSON(qw422016 *qt422016.Writer, s *otelpb.Span) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:87
	qw422016.N().S(`{"traceId":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:89
	qw422016.N().Q(hexIDToBase64(s.TraceID))
//line app/vtselect/traces/tempo/tracebyid.qtpl:89
	qw422016.N().S(`,"spanId":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:90
	qw422016.N().Q(hexIDToBase64(s.SpanID))
//line app/vtselect/traces/tempo/tracebyid.qtpl:90
	qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:91
	if s.ParentSpanID != "" {
//line app/vtselect/traces/tempo/tracebyid.qtpl:91
		qw422016.N().S(`"parentSpanId":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:92
		qw422016.N().Q(hexIDToBase64(s.ParentSpanID))
//line app/vtselect/traces/tempo/tracebyid.qtpl:92
		qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:93
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:93
	qw422016.N().S(`"name":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:94
	qw422016.N().Q(s.Name)
//line app/vtselect/traces/tempo/tracebyid.qtpl:94
	qw422016.N().S(`,"kind":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:95
	qw422016.N().Q(spanKindName(s.Kind))
//line app/vtselect/traces/tempo/tracebyid.qtpl:95
	qw422016.N().S(`,"startTimeUnixNano":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:96
	qw422016.N().Q(strconv.FormatUint(s.StartTimeUnixNano, 10))
//line app/vtselect/traces/tempo/tracebyid.qtpl:96
	qw422016.N().S(`,"endTimeUnixNano":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:97
	qw422016.N().Q(strconv.FormatUint(s.EndTimeUnixNano, 10))
//line app/vtselect/traces/tempo/tracebyid.qtpl:97
	qw422016.N().S(`,"attributes":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:98
	streamkeyValueListJSON(qw422016, s.Attributes)
//line app/vtselect/traces/tempo/tracebyid.qtpl:98
	qw422016.N().S(`,"status":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:99
	streamstatusJSON(qw422016, s.Status)
//line app/vtselect/traces/tempo/tracebyid.qtpl:100
	if len(s.Events) > 0 {
//line app/vtselect/traces/tempo/tracebyid.qtpl:100
		qw422016.N().S(`,"events":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:101
		streameventsArrayJSON(qw422016, s.Events)
//line app/vtselect/traces/tempo/tracebyid.qtpl:102
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:103
	if len(s.Links) > 0 {
//line app/vtselect/traces/tempo/tracebyid.qtpl:103
		qw422016.N().S(`,"links":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:104
		streamlinksArrayJSON(qw422016, s.Links)
//line app/vtselect/traces/tempo/tracebyid.qtpl:105
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:105
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:107
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:107
func writespanJSON(qq422016 qtio422016.Writer, s *otelpb.Span) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:107
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:107
	streamspanJSON(qw422016, s)
//line app/vtselect/traces/tempo/tracebyid.qtpl:107
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:107
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:107
func spanJSON(s *otelpb.Span) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:107
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:107
	writespanJSON(qb422016, s)
//line app/vtselect/traces/tempo/tracebyid.qtpl:107
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:107
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:107
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:107
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:109
func streamstatusJSON(qw422016 *qt422016.Writer, st otelpb.Status) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:109
	qw422016.N().S(`{`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:111
	if st.Message != "" {
//line app/vtselect/traces/tempo/tracebyid.qtpl:111
		qw422016.N().S(`"message":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:112
		qw422016.N().Q(st.Message)
//line app/vtselect/traces/tempo/tracebyid.qtpl:112
		if st.Code != 0 {
//line app/vtselect/traces/tempo/tracebyid.qtpl:112
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:112
		}
//line app/vtselect/traces/tempo/tracebyid.qtpl:113
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:114
	if st.Code != 0 {
//line app/vtselect/traces/tempo/tracebyid.qtpl:114
		qw422016.N().S(`"code":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:115
		qw422016.N().Q(statusCodeName(st.Code))
//line app/vtselect/traces/tempo/tracebyid.qtpl:116
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:116
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:118
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:118
func writestatusJSON(qq422016 qtio422016.Writer, st otelpb.Status) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:118
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:118
	streamstatusJSON(qw422016, st)
//line app/vtselect/traces/tempo/tracebyid.qtpl:118
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:118
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:118
func statusJSON(st otelpb.Status) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:118
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:118
	writestatusJSON(qb422016, st)
//line app/vtselect/traces/tempo/tracebyid.qtpl:118
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:118
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:118
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:118
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:120
func streameventsArrayJSON(qw422016 *qt422016.Writer, events []*otelpb.SpanEvent) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:120
	qw422016.N().S(`[`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:122
	if len(events) > 0 {
//line app/vtselect/traces/tempo/tracebyid.qtpl:123
		streameventJSON(qw422016, events[0])
//line app/vtselect/traces/tempo/tracebyid.qtpl:124
		for _, e := range events[1:] {
//line app/vtselect/traces/tempo/tracebyid.qtpl:124
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:125
			streameventJSON(qw422016, e)
//line app/vtselect/traces/tempo/tracebyid.qtpl:126
		}
//line app/vtselect/traces/tempo/tracebyid.qtpl:127
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:127
	qw422016.N().S(`]`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:129
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:129
func writeeventsArrayJSON(qq422016 qtio422016.Writer, events []*otelpb.SpanEvent) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:129
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:129
	streameventsArrayJSON(qw422016, events)
//line app/vtselect/traces/tempo/tracebyid.qtpl:129
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:129
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:129
func eventsArrayJSON(events []*otelpb.SpanEvent) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:129
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:129
	writeeventsArrayJSON(qb422016, events)
//line app/vtselect/traces/tempo/tracebyid.qtpl:129
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:129
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:129
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:129
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:131
func streameventJSON(qw422016 *qt422016.Writer, e *otelpb.SpanEvent) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:131
	qw422016.N().S(`{"timeUnixNano":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:133
	qw422016.N().Q(strconv.FormatUint(e.TimeUnixNano, 10))
//line app/vtselect/traces/tempo/tracebyid.qtpl:133
	qw422016.N().S(`,"name":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:134
	qw422016.N().Q(e.Name)
//line app/vtselect/traces/tempo/tracebyid.qtpl:134
	qw422016.N().S(`,"attributes":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:135
	streamkeyValueListJSON(qw422016, e.Attributes)
//line app/vtselect/traces/tempo/tracebyid.qtpl:135
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:137
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:137
func writeeventJSON(qq422016 qtio422016.Writer, e *otelpb.SpanEvent) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:137
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:137
	streameventJSON(qw422016, e)
//line app/vtselect/traces/tempo/tracebyid.qtpl:137
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:137
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:137
func eventJSON(e *otelpb.SpanEvent) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:137
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:137
	writeeventJSON(qb422016, e)
//line app/vtselect/traces/tempo/tracebyid.qtpl:137
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:137
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:137
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:137
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:139
func streamlinksArrayJSON(qw422016 *qt422016.Writer, links []*otelpb.SpanLink) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:139
	qw422016.N().S(`[`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:141
	if len(links) > 0 {
//line app/vtselect/traces/tempo/tracebyid.qtpl:142
		streamlinkJSON(qw422016, links[0])
//line app/vtselect/traces/tempo/tracebyid.qtpl:143
		for _, l := range links[1:] {
//line app/vtselect/traces/tempo/tracebyid.qtpl:143
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:144
			streamlinkJSON(qw422016, l)
//line app/vtselect/traces/tempo/tracebyid.qtpl:145
		}
//line app/vtselect/traces/tempo/tracebyid.qtpl:146
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:146
	qw422016.N().S(`]`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:148
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:148
func writelinksArrayJSON(qq422016 qtio422016.Writer, links []*otelpb.SpanLink) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:148
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:148
	streamlinksArrayJSON(qw422016, links)
//line app/vtselect/traces/tempo/tracebyid.qtpl:148
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:148
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:148
func linksArrayJSON(links []*otelpb.SpanLink) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:148
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:148
	writelinksArrayJSON(qb422016, links)
//line app/vtselect/traces/tempo/tracebyid.qtpl:148
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:148
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:148
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:148
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:150
func streamlinkJSON(qw422016 *qt422016.Writer, l *otelpb.SpanLink) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:150
	qw422016.N().S(`{"traceId":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:152
	qw422016.N().Q(hexIDToBase64(l.TraceID))
//line app/vtselect/traces/tempo/tracebyid.qtpl:152
	qw422016.N().S(`,"spanId":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:153
	qw422016.N().Q(hexIDToBase64(l.SpanID))
//line app/vtselect/traces/tempo/tracebyid.qtpl:153
	qw422016.N().S(`,"attributes":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:154
	streamkeyValueListJSON(qw422016, l.Attributes)
//line app/vtselect/traces/tempo/tracebyid.qtpl:154
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:156
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:156
func writelinkJSON(qq422016 qtio422016.Writer, l *otelpb.SpanLink) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:156
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:156
	streamlinkJSON(qw422016, l)
//line app/vtselect/traces/tempo/tracebyid.qtpl:156
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:156
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:156
func linkJSON(l *otelpb.SpanLink) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:156
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:156
	writelinkJSON(qb422016, l)
//line app/vtselect/traces/tempo/tracebyid.qtpl:156
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:156
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:156
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:156
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:158
func streamkeyValueListJSON(qw422016 *qt422016.Writer, kvs []*otelpb.KeyValue) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:158
	qw422016.N().S(`[`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:160
	if len(kvs) > 0 {
//line app/vtselect/traces/tempo/tracebyid.qtpl:161
		streamkeyValueJSON(qw422016, kvs[0])
//line app/vtselect/traces/tempo/tracebyid.qtpl:162
		for _, kv := range kvs[1:] {
//line app/vtselect/traces/tempo/tracebyid.qtpl:162
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:163
			streamkeyValueJSON(qw422016, kv)
//line app/vtselect/traces/tempo/tracebyid.qtpl:164
		}
//line app/vtselect/traces/tempo/tracebyid.qtpl:165
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:165
	qw422016.N().S(`]`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:167
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:167
func writekeyValueListJSON(qq422016 qtio422016.Writer, kvs []*otelpb.KeyValue) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:167
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:167
	streamkeyValueListJSON(qw422016, kvs)
//line app/vtselect/traces/tempo/tracebyid.qtpl:167
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:167
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:167
func keyValueListJSON(kvs []*otelpb.KeyValue) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:167
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:167
	writekeyValueListJSON(qb422016, kvs)
//line app/vtselect/traces/tempo/tracebyid.qtpl:167
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:167
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:167
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:167
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:169
func streamkeyValueJSON(qw422016 *qt422016.Writer, kv *otelpb.KeyValue) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:169
	qw422016.N().S(`{"key":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:171
	qw422016.N().Q(kv.Key)
//line app/vtselect/traces/tempo/tracebyid.qtpl:171
	qw422016.N().S(`,"value":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:172
	streamanyValueJSON(qw422016, kv.Value)
//line app/vtselect/traces/tempo/tracebyid.qtpl:172
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:174
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:174
func writekeyValueJSON(qq422016 qtio422016.Writer, kv *otelpb.KeyValue) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:174
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:174
	streamkeyValueJSON(qw422016, kv)
//line app/vtselect/traces/tempo/tracebyid.qtpl:174
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:174
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:174
func keyValueJSON(kv *otelpb.KeyValue) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:174
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:174
	writekeyValueJSON(qb422016, kv)
//line app/vtselect/traces/tempo/tracebyid.qtpl:174
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:174
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:174
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:174
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:176
func streamanyValueJSON(qw422016 *qt422016.Writer, v *otelpb.AnyValue) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:176
	qw422016.N().S(`{`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:178
	if v == nil {
//line app/vtselect/traces/tempo/tracebyid.qtpl:179
	} else if v.StringValue != nil {
//line app/vtselect/traces/tempo/tracebyid.qtpl:179
		qw422016.N().S(`"stringValue":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:180
		qw422016.N().Q(*v.StringValue)
//line app/vtselect/traces/tempo/tracebyid.qtpl:181
	} else if v.BoolValue != nil {
//line app/vtselect/traces/tempo/tracebyid.qtpl:181
		qw422016.N().S(`"boolValue":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:182
		if *v.BoolValue {
//line app/vtselect/traces/tempo/tracebyid.qtpl:182
			qw422016.N().S(`true`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:182
		} else {
//line app/vtselect/traces/tempo/tracebyid.qtpl:182
			qw422016.N().S(`false`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:182
		}
//line app/vtselect/traces/tempo/tracebyid.qtpl:183
	} else if v.IntValue != nil {
//line app/vtselect/traces/tempo/tracebyid.qtpl:183
		qw422016.N().S(`"intValue":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:184
		qw422016.N().Q(strconv.FormatInt(*v.IntValue, 10))
//line app/vtselect/traces/tempo/tracebyid.qtpl:185
	} else if v.DoubleValue != nil {
//line app/vtselect/traces/tempo/tracebyid.qtpl:185
		qw422016.N().S(`"doubleValue":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:186
		qw422016.N().F(*v.DoubleValue)
//line app/vtselect/traces/tempo/tracebyid.qtpl:187
	} else if v.BytesValue != nil {
//line app/vtselect/traces/tempo/tracebyid.qtpl:187
		qw422016.N().S(`"bytesValue":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:188
		qw422016.N().Q(bytesToBase64(*v.BytesValue))
//line app/vtselect/traces/tempo/tracebyid.qtpl:189
	} else if v.ArrayValue != nil {
//line app/vtselect/traces/tempo/tracebyid.qtpl:189
		qw422016.N().S(`"arrayValue":{"values":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:190
		streamanyValueArrayJSON(qw422016, v.ArrayValue.Values)
//line app/vtselect/traces/tempo/tracebyid.qtpl:190
		qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:191
	} else if v.KeyValueList != nil {
//line app/vtselect/traces/tempo/tracebyid.qtpl:191
		qw422016.N().S(`"kvlistValue":{"values":`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:192
		streamkeyValueListJSON(qw422016, v.KeyValueList.Values)
//line app/vtselect/traces/tempo/tracebyid.qtpl:192
		qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:193
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:193
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:195
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:195
func writeanyValueJSON(qq422016 qtio422016.Writer, v *otelpb.AnyValue) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:195
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:195
	streamanyValueJSON(qw422016, v)
//line app/vtselect/traces/tempo/tracebyid.qtpl:195
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:195
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:195
func anyValueJSON(v *otelpb.AnyValue) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:195
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:195
	writeanyValueJSON(qb422016, v)
//line app/vtselect/traces/tempo/tracebyid.qtpl:195
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:195
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:195
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:195
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:197
func streamanyValueArrayJSON(qw422016 *qt422016.Writer, values []*otelpb.AnyValue) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:197
	qw422016.N().S(`[`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:199
	if len(values) > 0 {
//line app/vtselect/traces/tempo/tracebyid.qtpl:200
		streamanyValueJSON(qw422016, values[0])
//line app/vtselect/traces/tempo/tracebyid.qtpl:201
		for _, v := range values[1:] {
//line app/vtselect/traces/tempo/tracebyid.qtpl:201
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:202
			streamanyValueJSON(qw422016, v)
//line app/vtselect/traces/tempo/tracebyid.qtpl:203
		}
//line app/vtselect/traces/tempo/tracebyid.qtpl:204
	}
//line app/vtselect/traces/tempo/tracebyid.qtpl:204
	qw422016.N().S(`]`)
//line app/vtselect/traces/tempo/tracebyid.qtpl:206
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:206
func writeanyValueArrayJSON(qq422016 qtio422016.Writer, values []*otelpb.AnyValue) {
//line app/vtselect/traces/tempo/tracebyid.qtpl:206
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:206
	streamanyValueArrayJSON(qw422016, values)
//line app/vtselect/traces/tempo/tracebyid.qtpl:206
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:206
}

//line app/vtselect/traces/tempo/tracebyid.qtpl:206
func anyValueArrayJSON(values []*otelpb.AnyValue) string {
//line app/vtselect/traces/tempo/tracebyid.qtpl:206
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tracebyid.qtpl:206
	writeanyValueArrayJSON(qb422016, values)
//line app/vtselect/traces/tempo/tracebyid.qtpl:206
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tracebyid.qtpl:206
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tracebyid.qtpl:206
	return qs422016
//line app/vtselect/traces/tempo/tracebyid.qtpl:206
}
