export const STORAGE_PREFIX = "VLUI:" as const;

export const ALL_STORAGE_KEYS = [
  "AUTOCOMPLETE",
  "TIMEZONE",
  "DISABLED_DEFAULT_TIMEZONE",
  "THEME",
  "TRACES_LIMIT",
  "TRACES_MARKDOWN",
  "TRACES_ANSI",
  "SERVER_URL",
  "RAW_JSON_LIVE_VIEW",
  "TRACES_OVERRIDE_TIME",
  "TRACES_TABLE_DRAWER",
  "TRACE_DETAIL_PANE_WIDTH",
  "TRACE_INFO_DRAWER_WIDTH",
  "TRACES_QUERY_HISTORY",
  "TRACES_FILTER_SIDEBAR_HIDDEN"
] as const;

export const TABLE_KEYS = {
  COLS_PREFS: "TRACES_TABLE_COLS_PREFS",
  COLS_VIEW: "TRACES_TABLE_COLS_VIEW",
} as const;

