// Code generated by qtc from "apiv3.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vtselect/traces/jaeger/apiv3.qtpl:1
package jaeger

//line app/vtselect/traces/jaeger/apiv3.qtpl:1
import (
	"sort"

	otelpb "github.com/VictoriaMetrics/VictoriaTraces/lib/protoparser/opentelemetry/pb"
)

//line app/vtselect/traces/jaeger/apiv3.qtpl:15
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vtselect/traces/jaeger/apiv3.qtpl:15
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vtselect/traces/jaeger/apiv3.qtpl:15
func StreamGetServicesResponseV3(qw422016 *qt422016.Writer, serviceList []string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:15
	qw422016.N().S(`{`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:18
	sort.Slice(serviceList, func(i, j int) bool { return serviceList[i] < serviceList[j] })

//line app/vtselect/traces/jaeger/apiv3.qtpl:19
	qw422016.N().S(`"services":[`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:21
	for i, service := range serviceList {
//line app/vtselect/traces/jaeger/apiv3.qtpl:22
		if i > 0 {
//line app/vtselect/traces/jaeger/apiv3.qtpl:22
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:22
		}
//line app/vtselect/traces/jaeger/apiv3.qtpl:23
		qw422016.N().Q(service)
//line app/vtselect/traces/jaeger/apiv3.qtpl:24
	}
//line app/vtselect/traces/jaeger/apiv3.qtpl:24
	qw422016.N().S(`]}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:27
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:27
func WriteGetServicesResponseV3(qq422016 qtio422016.Writer, serviceList []string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:27
	StreamGetServicesResponseV3(qw422016, serviceList)
//line app/vtselect/traces/jaeger/apiv3.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:27
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:27
func GetServicesResponseV3(serviceList []string) string {
//line app/vtselect/traces/jaeger/apiv3.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/apiv3.qtpl:27
	WriteGetServicesResponseV3(qb422016, serviceList)
//line app/vtselect/traces/jaeger/apiv3.qtpl:27
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/apiv3.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:27
	return qs422016
//line app/vtselect/traces/jaeger/apiv3.qtpl:27
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:29
func StreamGetOperationsResponseV3(qw422016 *qt422016.Writer, operationList []string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:29
	qw422016.N().S(`{`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:32
	sort.Slice(operationList, func(i, j int) bool { return operationList[i] < operationList[j] })

//line app/vtselect/traces/jaeger/apiv3.qtpl:33
	qw422016.N().S(`"operations":[`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:35
	for i, operation := range operationList {
//line app/vtselect/traces/jaeger/apiv3.qtpl:36
		if i > 0 {
//line app/vtselect/traces/jaeger/apiv3.qtpl:36
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:36
		}
//line app/vtselect/traces/jaeger/apiv3.qtpl:36
		qw422016.N().S(`{"name":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:37
		qw422016.N().Q(operation)
//line app/vtselect/traces/jaeger/apiv3.qtpl:37
		qw422016.N().S(`,"spanKind":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:37
		qw422016.N().Q(defaultSpanKind)
//line app/vtselect/traces/jaeger/apiv3.qtpl:37
		qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:38
	}
//line app/vtselect/traces/jaeger/apiv3.qtpl:38
	qw422016.N().S(`]}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:41
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:41
func WriteGetOperationsResponseV3(qq422016 qtio422016.Writer, operationList []string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:41
	StreamGetOperationsResponseV3(qw422016, operationList)
//line app/vtselect/traces/jaeger/apiv3.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:41
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:41
func GetOperationsResponseV3(operationList []string) string {
//line app/vtselect/traces/jaeger/apiv3.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/apiv3.qtpl:41
	WriteGetOperationsResponseV3(qb422016, operationList)
//line app/vtselect/traces/jaeger/apiv3.qtpl:41
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/apiv3.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:41
	return qs422016
//line app/vtselect/traces/jaeger/apiv3.qtpl:41
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:43
func StreamTracesResponseV3(qw422016 *qt422016.Writer, rss []*otelpb.ResourceSpans) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:43
	qw422016.N().S(`{"result":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:45
	otelpb.StreamTracesDataJSON(qw422016, rss)
//line app/vtselect/traces/jaeger/apiv3.qtpl:45
	qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:47
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:47
func WriteTracesResponseV3(qq422016 qtio422016.Writer, rss []*otelpb.ResourceSpans) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:47
	StreamTracesResponseV3(qw422016, rss)
//line app/vtselect/traces/jaeger/apiv3.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:47
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:47
func TracesResponseV3(rss []*otelpb.ResourceSpans) string {
//line app/vtselect/traces/jaeger/apiv3.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/apiv3.qtpl:47
	WriteTracesResponseV3(qb422016, rss)
//line app/vtselect/traces/jaeger/apiv3.qtpl:47
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/apiv3.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:47
	return qs422016
//line app/vtselect/traces/jaeger/apiv3.qtpl:47
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:49
func StreamErrorResponseV3(qw422016 *qt422016.Writer, httpCode int, message string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:49
	qw422016.N().S(`{"error":{"httpCode":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:52
	qw422016.N().D(httpCode)
//line app/vtselect/traces/jaeger/apiv3.qtpl:52
	qw422016.N().S(`,"message":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:53
	qw422016.N().Q(message)
//line app/vtselect/traces/jaeger/apiv3.qtpl:53
	qw422016.N().S(`}}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:56
func WriteErrorResponseV3(qq422016 qtio422016.Writer, httpCode int, message string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
	StreamErrorResponseV3(qw422016, httpCode, message)
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:56
func ErrorResponseV3(httpCode int, message string) string {
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
	WriteErrorResponseV3(qb422016, httpCode, message)
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
	return qs422016
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
}
