// Code generated by qtc from "apiv3.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vtselect/traces/jaeger/apiv3.qtpl:1
package jaeger

//line app/vtselect/traces/jaeger/apiv3.qtpl:1
import (
	"sort"
	"strconv"

	otelpb "github.com/VictoriaMetrics/VictoriaTraces/lib/protoparser/opentelemetry/pb"
)

//line app/vtselect/traces/jaeger/apiv3.qtpl:16
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vtselect/traces/jaeger/apiv3.qtpl:16
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vtselect/traces/jaeger/apiv3.qtpl:16
func StreamGetServicesResponseV3(qw422016 *qt422016.Writer, serviceList []string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:16
	qw422016.N().S(`{`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:19
	sort.Slice(serviceList, func(i, j int) bool { return serviceList[i] < serviceList[j] })

//line app/vtselect/traces/jaeger/apiv3.qtpl:20
	qw422016.N().S(`"services":[`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:22
	for i, service := range serviceList {
//line app/vtselect/traces/jaeger/apiv3.qtpl:23
		if i > 0 {
//line app/vtselect/traces/jaeger/apiv3.qtpl:23
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:23
		}
//line app/vtselect/traces/jaeger/apiv3.qtpl:24
		qw422016.N().Q(service)
//line app/vtselect/traces/jaeger/apiv3.qtpl:25
	}
//line app/vtselect/traces/jaeger/apiv3.qtpl:25
	qw422016.N().S(`]}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:28
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:28
func WriteGetServicesResponseV3(qq422016 qtio422016.Writer, serviceList []string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:28
	StreamGetServicesResponseV3(qw422016, serviceList)
//line app/vtselect/traces/jaeger/apiv3.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:28
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:28
func GetServicesResponseV3(serviceList []string) string {
//line app/vtselect/traces/jaeger/apiv3.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/apiv3.qtpl:28
	WriteGetServicesResponseV3(qb422016, serviceList)
//line app/vtselect/traces/jaeger/apiv3.qtpl:28
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/apiv3.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:28
	return qs422016
//line app/vtselect/traces/jaeger/apiv3.qtpl:28
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:30
func StreamGetOperationsResponseV3(qw422016 *qt422016.Writer, operationList []string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:30
	qw422016.N().S(`{`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:33
	sort.Slice(operationList, func(i, j int) bool { return operationList[i] < operationList[j] })

//line app/vtselect/traces/jaeger/apiv3.qtpl:34
	qw422016.N().S(`"operations":[`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:36
	for i, operation := range operationList {
//line app/vtselect/traces/jaeger/apiv3.qtpl:37
		if i > 0 {
//line app/vtselect/traces/jaeger/apiv3.qtpl:37
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:37
		}
//line app/vtselect/traces/jaeger/apiv3.qtpl:37
		qw422016.N().S(`{"name":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:38
		qw422016.N().Q(operation)
//line app/vtselect/traces/jaeger/apiv3.qtpl:38
		qw422016.N().S(`,"spanKind":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:38
		qw422016.N().Q(defaultSpanKind)
//line app/vtselect/traces/jaeger/apiv3.qtpl:38
		qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:39
	}
//line app/vtselect/traces/jaeger/apiv3.qtpl:39
	qw422016.N().S(`]}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:42
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:42
func WriteGetOperationsResponseV3(qq422016 qtio422016.Writer, operationList []string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:42
	StreamGetOperationsResponseV3(qw422016, operationList)
//line app/vtselect/traces/jaeger/apiv3.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:42
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:42
func GetOperationsResponseV3(operationList []string) string {
//line app/vtselect/traces/jaeger/apiv3.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/apiv3.qtpl:42
	WriteGetOperationsResponseV3(qb422016, operationList)
//line app/vtselect/traces/jaeger/apiv3.qtpl:42
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/apiv3.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:42
	return qs422016
//line app/vtselect/traces/jaeger/apiv3.qtpl:42
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:44
func StreamTracesResponseV3(qw422016 *qt422016.Writer, rss []*otelpb.ResourceSpans) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:44
	qw422016.N().S(`{"result":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:46
	otelpb.StreamTracesDataJSON(qw422016, rss)
//line app/vtselect/traces/jaeger/apiv3.qtpl:46
	qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:48
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:48
func WriteTracesResponseV3(qq422016 qtio422016.Writer, rss []*otelpb.ResourceSpans) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:48
	StreamTracesResponseV3(qw422016, rss)
//line app/vtselect/traces/jaeger/apiv3.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:48
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:48
func TracesResponseV3(rss []*otelpb.ResourceSpans) string {
//line app/vtselect/traces/jaeger/apiv3.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/apiv3.qtpl:48
	WriteTracesResponseV3(qb422016, rss)
//line app/vtselect/traces/jaeger/apiv3.qtpl:48
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/apiv3.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:48
	return qs422016
//line app/vtselect/traces/jaeger/apiv3.qtpl:48
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:53
func StreamTraceSummariesResponseV3(qw422016 *qt422016.Writer, summaries []traceSummaryV3) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:53
	qw422016.N().S(`{"summaries":[`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:56
	for i, s := range summaries {
//line app/vtselect/traces/jaeger/apiv3.qtpl:57
		if i > 0 {
//line app/vtselect/traces/jaeger/apiv3.qtpl:57
			qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:57
		}
//line app/vtselect/traces/jaeger/apiv3.qtpl:57
		qw422016.N().S(`{"traceId":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:59
		qw422016.N().Q(s.traceID)
//line app/vtselect/traces/jaeger/apiv3.qtpl:59
		qw422016.N().S(`,"rootServiceName":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:60
		qw422016.N().Q(s.rootServiceName)
//line app/vtselect/traces/jaeger/apiv3.qtpl:60
		qw422016.N().S(`,"rootOperationName":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:61
		qw422016.N().Q(s.rootOperationName)
//line app/vtselect/traces/jaeger/apiv3.qtpl:61
		qw422016.N().S(`,"minStartTimeUnixNano":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:62
		qw422016.N().Q(strconv.FormatUint(s.minStartTimeUnixNano, 10))
//line app/vtselect/traces/jaeger/apiv3.qtpl:62
		qw422016.N().S(`,"maxEndTimeUnixNano":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:63
		qw422016.N().Q(strconv.FormatUint(s.maxEndTimeUnixNano, 10))
//line app/vtselect/traces/jaeger/apiv3.qtpl:63
		qw422016.N().S(`,"spanCount":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:64
		qw422016.N().D(s.spanCount)
//line app/vtselect/traces/jaeger/apiv3.qtpl:64
		qw422016.N().S(`,"errorSpanCount":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:65
		qw422016.N().D(s.errorSpanCount)
//line app/vtselect/traces/jaeger/apiv3.qtpl:65
		qw422016.N().S(`,"orphanSpanCount":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:66
		qw422016.N().D(s.orphanSpanCount)
//line app/vtselect/traces/jaeger/apiv3.qtpl:66
		qw422016.N().S(`,"services":[`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:68
		for j, svc := range s.services {
//line app/vtselect/traces/jaeger/apiv3.qtpl:69
			if j > 0 {
//line app/vtselect/traces/jaeger/apiv3.qtpl:69
				qw422016.N().S(`,`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:69
			}
//line app/vtselect/traces/jaeger/apiv3.qtpl:69
			qw422016.N().S(`{"name":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:71
			qw422016.N().Q(svc.name)
//line app/vtselect/traces/jaeger/apiv3.qtpl:71
			qw422016.N().S(`,"spanCount":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:72
			qw422016.N().D(svc.spanCount)
//line app/vtselect/traces/jaeger/apiv3.qtpl:72
			qw422016.N().S(`,"errorSpanCount":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:73
			qw422016.N().D(svc.errorSpanCount)
//line app/vtselect/traces/jaeger/apiv3.qtpl:73
			qw422016.N().S(`}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:75
		}
//line app/vtselect/traces/jaeger/apiv3.qtpl:75
		qw422016.N().S(`]}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:78
	}
//line app/vtselect/traces/jaeger/apiv3.qtpl:78
	qw422016.N().S(`]}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:81
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:81
func WriteTraceSummariesResponseV3(qq422016 qtio422016.Writer, summaries []traceSummaryV3) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:81
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:81
	StreamTraceSummariesResponseV3(qw422016, summaries)
//line app/vtselect/traces/jaeger/apiv3.qtpl:81
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:81
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:81
func TraceSummariesResponseV3(summaries []traceSummaryV3) string {
//line app/vtselect/traces/jaeger/apiv3.qtpl:81
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/apiv3.qtpl:81
	WriteTraceSummariesResponseV3(qb422016, summaries)
//line app/vtselect/traces/jaeger/apiv3.qtpl:81
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/apiv3.qtpl:81
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:81
	return qs422016
//line app/vtselect/traces/jaeger/apiv3.qtpl:81
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:83
func StreamErrorResponseV3(qw422016 *qt422016.Writer, httpCode int, message string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:83
	qw422016.N().S(`{"error":{"httpCode":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:86
	qw422016.N().D(httpCode)
//line app/vtselect/traces/jaeger/apiv3.qtpl:86
	qw422016.N().S(`,"message":`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:87
	qw422016.N().Q(message)
//line app/vtselect/traces/jaeger/apiv3.qtpl:87
	qw422016.N().S(`}}`)
//line app/vtselect/traces/jaeger/apiv3.qtpl:90
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:90
func WriteErrorResponseV3(qq422016 qtio422016.Writer, httpCode int, message string) {
//line app/vtselect/traces/jaeger/apiv3.qtpl:90
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:90
	StreamErrorResponseV3(qw422016, httpCode, message)
//line app/vtselect/traces/jaeger/apiv3.qtpl:90
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:90
}

//line app/vtselect/traces/jaeger/apiv3.qtpl:90
func ErrorResponseV3(httpCode int, message string) string {
//line app/vtselect/traces/jaeger/apiv3.qtpl:90
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/jaeger/apiv3.qtpl:90
	WriteErrorResponseV3(qb422016, httpCode, message)
//line app/vtselect/traces/jaeger/apiv3.qtpl:90
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/jaeger/apiv3.qtpl:90
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/jaeger/apiv3.qtpl:90
	return qs422016
//line app/vtselect/traces/jaeger/apiv3.qtpl:90
}
