// Code generated by qtc from "jaeger.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line jaeger.qtpl:1
package jaeger

//line jaeger.qtpl:1
import (
	"sort"
)

//line jaeger.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line jaeger.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line jaeger.qtpl:7
func StreamGetServicesResponse(qw422016 *qt422016.Writer, serviceList []string) {
//line jaeger.qtpl:7
	qw422016.N().S(`{`)
//line jaeger.qtpl:10
	sort.Slice(serviceList, func(i, j int) bool { return serviceList[i] < serviceList[j] })

//line jaeger.qtpl:11
	qw422016.N().S(`"data":[`)
//line jaeger.qtpl:13
	if len(serviceList) > 0 {
//line jaeger.qtpl:14
		qw422016.N().Q(serviceList[0])
//line jaeger.qtpl:15
		for _, service := range serviceList[1:] {
//line jaeger.qtpl:15
			qw422016.N().S(`,`)
//line jaeger.qtpl:16
			qw422016.N().Q(service)
//line jaeger.qtpl:17
		}
//line jaeger.qtpl:18
	}
//line jaeger.qtpl:18
	qw422016.N().S(`],"errors": null,"limit": 0,"offset": 0,"total":`)
//line jaeger.qtpl:23
	qw422016.N().D(len(serviceList))
//line jaeger.qtpl:23
	qw422016.N().S(`}`)
//line jaeger.qtpl:25
}

//line jaeger.qtpl:25
func WriteGetServicesResponse(qq422016 qtio422016.Writer, serviceList []string) {
//line jaeger.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jaeger.qtpl:25
	StreamGetServicesResponse(qw422016, serviceList)
//line jaeger.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line jaeger.qtpl:25
}

//line jaeger.qtpl:25
func GetServicesResponse(serviceList []string) string {
//line jaeger.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line jaeger.qtpl:25
	WriteGetServicesResponse(qb422016, serviceList)
//line jaeger.qtpl:25
	qs422016 := string(qb422016.B)
//line jaeger.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line jaeger.qtpl:25
	return qs422016
//line jaeger.qtpl:25
}

//line jaeger.qtpl:27
func StreamGetOperationsResponse(qw422016 *qt422016.Writer, operationList []string) {
//line jaeger.qtpl:27
	qw422016.N().S(`{`)
//line jaeger.qtpl:30
	sort.Slice(operationList, func(i, j int) bool { return operationList[i] < operationList[j] })

//line jaeger.qtpl:31
	qw422016.N().S(`"data":[`)
//line jaeger.qtpl:33
	if len(operationList) > 0 {
//line jaeger.qtpl:34
		qw422016.N().Q(operationList[0])
//line jaeger.qtpl:35
		for _, operation := range operationList[1:] {
//line jaeger.qtpl:35
			qw422016.N().S(`,`)
//line jaeger.qtpl:36
			qw422016.N().Q(operation)
//line jaeger.qtpl:37
		}
//line jaeger.qtpl:38
	}
//line jaeger.qtpl:38
	qw422016.N().S(`],"errors": null,"limit": 0,"offset": 0,"total":`)
//line jaeger.qtpl:43
	qw422016.N().D(len(operationList))
//line jaeger.qtpl:43
	qw422016.N().S(`}`)
//line jaeger.qtpl:45
}

//line jaeger.qtpl:45
func WriteGetOperationsResponse(qq422016 qtio422016.Writer, operationList []string) {
//line jaeger.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jaeger.qtpl:45
	StreamGetOperationsResponse(qw422016, operationList)
//line jaeger.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line jaeger.qtpl:45
}

//line jaeger.qtpl:45
func GetOperationsResponse(operationList []string) string {
//line jaeger.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line jaeger.qtpl:45
	WriteGetOperationsResponse(qb422016, operationList)
//line jaeger.qtpl:45
	qs422016 := string(qb422016.B)
//line jaeger.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line jaeger.qtpl:45
	return qs422016
//line jaeger.qtpl:45
}

//line jaeger.qtpl:47
func StreamGetTracesResponse(qw422016 *qt422016.Writer, traces []*trace) {
//line jaeger.qtpl:47
	qw422016.N().S(`{"data":[`)
//line jaeger.qtpl:50
	if len(traces) > 0 && len(traces[0].spans) > 0 {
//line jaeger.qtpl:51
		streamtraceJson(qw422016, traces[0])
//line jaeger.qtpl:52
		for _, trace := range traces[1:] {
//line jaeger.qtpl:53
			if len(trace.spans) > 0 {
//line jaeger.qtpl:53
				qw422016.N().S(`,`)
//line jaeger.qtpl:54
				streamtraceJson(qw422016, trace)
//line jaeger.qtpl:55
			}
//line jaeger.qtpl:56
		}
//line jaeger.qtpl:57
	}
//line jaeger.qtpl:57
	qw422016.N().S(`],"errors": null,"limit": 0,"offset": 0,"total":`)
//line jaeger.qtpl:62
	qw422016.N().D(len(traces))
//line jaeger.qtpl:62
	qw422016.N().S(`}`)
//line jaeger.qtpl:64
}

//line jaeger.qtpl:64
func WriteGetTracesResponse(qq422016 qtio422016.Writer, traces []*trace) {
//line jaeger.qtpl:64
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jaeger.qtpl:64
	StreamGetTracesResponse(qw422016, traces)
//line jaeger.qtpl:64
	qt422016.ReleaseWriter(qw422016)
//line jaeger.qtpl:64
}

//line jaeger.qtpl:64
func GetTracesResponse(traces []*trace) string {
//line jaeger.qtpl:64
	qb422016 := qt422016.AcquireByteBuffer()
//line jaeger.qtpl:64
	WriteGetTracesResponse(qb422016, traces)
//line jaeger.qtpl:64
	qs422016 := string(qb422016.B)
//line jaeger.qtpl:64
	qt422016.ReleaseByteBuffer(qb422016)
//line jaeger.qtpl:64
	return qs422016
//line jaeger.qtpl:64
}

//line jaeger.qtpl:66
func StreamGetDependenciesResponse(qw422016 *qt422016.Writer, dependencies []*dependencyLink) {
//line jaeger.qtpl:66
	qw422016.N().S(`{"data":[`)
//line jaeger.qtpl:69
	if len(dependencies) > 0 {
//line jaeger.qtpl:70
		streamdependencyJson(qw422016, dependencies[0])
//line jaeger.qtpl:71
		for _, dependency := range dependencies[1:] {
//line jaeger.qtpl:71
			qw422016.N().S(`,`)
//line jaeger.qtpl:72
			streamdependencyJson(qw422016, dependency)
//line jaeger.qtpl:73
		}
//line jaeger.qtpl:74
	}
//line jaeger.qtpl:74
	qw422016.N().S(`],"errors": null,"limit": 0,"offset": 0,"total":`)
//line jaeger.qtpl:79
	qw422016.N().D(len(dependencies))
//line jaeger.qtpl:79
	qw422016.N().S(`}`)
//line jaeger.qtpl:81
}

//line jaeger.qtpl:81
func WriteGetDependenciesResponse(qq422016 qtio422016.Writer, dependencies []*dependencyLink) {
//line jaeger.qtpl:81
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jaeger.qtpl:81
	StreamGetDependenciesResponse(qw422016, dependencies)
//line jaeger.qtpl:81
	qt422016.ReleaseWriter(qw422016)
//line jaeger.qtpl:81
}

//line jaeger.qtpl:81
func GetDependenciesResponse(dependencies []*dependencyLink) string {
//line jaeger.qtpl:81
	qb422016 := qt422016.AcquireByteBuffer()
//line jaeger.qtpl:81
	WriteGetDependenciesResponse(qb422016, dependencies)
//line jaeger.qtpl:81
	qs422016 := string(qb422016.B)
//line jaeger.qtpl:81
	qt422016.ReleaseByteBuffer(qb422016)
//line jaeger.qtpl:81
	return qs422016
//line jaeger.qtpl:81
}

//line jaeger.qtpl:83
func streamdependencyJson(qw422016 *qt422016.Writer, dependency *dependencyLink) {
//line jaeger.qtpl:83
	qw422016.N().S(`{"parent":`)
//line jaeger.qtpl:85
	qw422016.N().Q(dependency.parent)
//line jaeger.qtpl:85
	qw422016.N().S(`,"child":`)
//line jaeger.qtpl:86
	qw422016.N().Q(dependency.child)
//line jaeger.qtpl:86
	qw422016.N().S(`,"callCount":`)
//line jaeger.qtpl:87
	qw422016.N().DUL(dependency.callCount)
//line jaeger.qtpl:87
	qw422016.N().S(`}`)
//line jaeger.qtpl:89
}

//line jaeger.qtpl:89
func writedependencyJson(qq422016 qtio422016.Writer, dependency *dependencyLink) {
//line jaeger.qtpl:89
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jaeger.qtpl:89
	streamdependencyJson(qw422016, dependency)
//line jaeger.qtpl:89
	qt422016.ReleaseWriter(qw422016)
//line jaeger.qtpl:89
}

//line jaeger.qtpl:89
func dependencyJson(dependency *dependencyLink) string {
//line jaeger.qtpl:89
	qb422016 := qt422016.AcquireByteBuffer()
//line jaeger.qtpl:89
	writedependencyJson(qb422016, dependency)
//line jaeger.qtpl:89
	qs422016 := string(qb422016.B)
//line jaeger.qtpl:89
	qt422016.ReleaseByteBuffer(qb422016)
//line jaeger.qtpl:89
	return qs422016
//line jaeger.qtpl:89
}

//line jaeger.qtpl:91
func streamtraceJson(qw422016 *qt422016.Writer, trace *trace) {
//line jaeger.qtpl:91
	qw422016.N().S(`{"processes": {`)
//line jaeger.qtpl:94
	if len(trace.processMap) > 0 {
//line jaeger.qtpl:95
		qw422016.N().Q(trace.processMap[0].processID)
//line jaeger.qtpl:95
		qw422016.N().S(`:`)
//line jaeger.qtpl:95
		streamprocessJson(qw422016, trace.processMap[0].process)
//line jaeger.qtpl:96
		for _, v := range trace.processMap[1:] {
//line jaeger.qtpl:96
			qw422016.N().S(`,`)
//line jaeger.qtpl:97
			qw422016.N().Q(v.processID)
//line jaeger.qtpl:97
			qw422016.N().S(`:`)
//line jaeger.qtpl:97
			streamprocessJson(qw422016, v.process)
//line jaeger.qtpl:98
		}
//line jaeger.qtpl:99
	}
//line jaeger.qtpl:99
	qw422016.N().S(`},"spans": [`)
//line jaeger.qtpl:102
	if len(trace.spans) > 0 {
//line jaeger.qtpl:103
		streamspanJson(qw422016, trace.spans[0])
//line jaeger.qtpl:104
		for _, v := range trace.spans[1:] {
//line jaeger.qtpl:104
			qw422016.N().S(`,`)
//line jaeger.qtpl:105
			streamspanJson(qw422016, v)
//line jaeger.qtpl:106
		}
//line jaeger.qtpl:107
	}
//line jaeger.qtpl:107
	qw422016.N().S(`],"traceID":`)
//line jaeger.qtpl:109
	qw422016.N().Q(trace.spans[0].traceID)
//line jaeger.qtpl:109
	qw422016.N().S(`,"warnings": null}`)
//line jaeger.qtpl:112
}

//line jaeger.qtpl:112
func writetraceJson(qq422016 qtio422016.Writer, trace *trace) {
//line jaeger.qtpl:112
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jaeger.qtpl:112
	streamtraceJson(qw422016, trace)
//line jaeger.qtpl:112
	qt422016.ReleaseWriter(qw422016)
//line jaeger.qtpl:112
}

//line jaeger.qtpl:112
func traceJson(trace *trace) string {
//line jaeger.qtpl:112
	qb422016 := qt422016.AcquireByteBuffer()
//line jaeger.qtpl:112
	writetraceJson(qb422016, trace)
//line jaeger.qtpl:112
	qs422016 := string(qb422016.B)
//line jaeger.qtpl:112
	qt422016.ReleaseByteBuffer(qb422016)
//line jaeger.qtpl:112
	return qs422016
//line jaeger.qtpl:112
}

//line jaeger.qtpl:114
func streamprocessJson(qw422016 *qt422016.Writer, process process) {
//line jaeger.qtpl:114
	qw422016.N().S(`{"serviceName":`)
//line jaeger.qtpl:116
	qw422016.N().Q(process.serviceName)
//line jaeger.qtpl:116
	qw422016.N().S(`,"tags": [`)
//line jaeger.qtpl:118
	if len(process.tags) > 0 {
//line jaeger.qtpl:119
		streamtagJson(qw422016, process.tags[0])
//line jaeger.qtpl:120
		for _, v := range process.tags[1:] {
//line jaeger.qtpl:120
			qw422016.N().S(`,`)
//line jaeger.qtpl:121
			streamtagJson(qw422016, v)
//line jaeger.qtpl:122
		}
//line jaeger.qtpl:123
	}
//line jaeger.qtpl:123
	qw422016.N().S(`]}`)
//line jaeger.qtpl:126
}

//line jaeger.qtpl:126
func writeprocessJson(qq422016 qtio422016.Writer, process process) {
//line jaeger.qtpl:126
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jaeger.qtpl:126
	streamprocessJson(qw422016, process)
//line jaeger.qtpl:126
	qt422016.ReleaseWriter(qw422016)
//line jaeger.qtpl:126
}

//line jaeger.qtpl:126
func processJson(process process) string {
//line jaeger.qtpl:126
	qb422016 := qt422016.AcquireByteBuffer()
//line jaeger.qtpl:126
	writeprocessJson(qb422016, process)
//line jaeger.qtpl:126
	qs422016 := string(qb422016.B)
//line jaeger.qtpl:126
	qt422016.ReleaseByteBuffer(qb422016)
//line jaeger.qtpl:126
	return qs422016
//line jaeger.qtpl:126
}

//line jaeger.qtpl:128
func streamspanJson(qw422016 *qt422016.Writer, span *span) {
//line jaeger.qtpl:128
	qw422016.N().S(`{"duration":`)
//line jaeger.qtpl:130
	qw422016.N().DL(span.duration)
//line jaeger.qtpl:130
	qw422016.N().S(`,"logs":[`)
//line jaeger.qtpl:132
	if len(span.logs) > 0 {
//line jaeger.qtpl:133
		streamlogJson(qw422016, span.logs[0])
//line jaeger.qtpl:134
		for _, v := range span.logs[1:] {
//line jaeger.qtpl:134
			qw422016.N().S(`,`)
//line jaeger.qtpl:135
			streamlogJson(qw422016, v)
//line jaeger.qtpl:136
		}
//line jaeger.qtpl:137
	}
//line jaeger.qtpl:137
	qw422016.N().S(`],"operationName":`)
//line jaeger.qtpl:139
	qw422016.N().Q(span.operationName)
//line jaeger.qtpl:139
	qw422016.N().S(`,"processID":`)
//line jaeger.qtpl:140
	qw422016.N().Q(span.processID)
//line jaeger.qtpl:140
	qw422016.N().S(`,"references": [`)
//line jaeger.qtpl:142
	if len(span.references) > 0 {
//line jaeger.qtpl:143
		streamspanRefJson(qw422016, span.references[0])
//line jaeger.qtpl:144
		for _, v := range span.references[1:] {
//line jaeger.qtpl:144
			qw422016.N().S(`,`)
//line jaeger.qtpl:145
			streamspanRefJson(qw422016, v)
//line jaeger.qtpl:146
		}
//line jaeger.qtpl:147
	}
//line jaeger.qtpl:147
	qw422016.N().S(`],"spanID":`)
//line jaeger.qtpl:149
	qw422016.N().Q(span.spanID)
//line jaeger.qtpl:149
	qw422016.N().S(`,"startTime":`)
//line jaeger.qtpl:150
	qw422016.N().DL(span.startTime)
//line jaeger.qtpl:150
	qw422016.N().S(`,"tags": [`)
//line jaeger.qtpl:152
	if len(span.tags) > 0 {
//line jaeger.qtpl:153
		streamtagJson(qw422016, span.tags[0])
//line jaeger.qtpl:154
		for _, v := range span.tags[1:] {
//line jaeger.qtpl:154
			qw422016.N().S(`,`)
//line jaeger.qtpl:155
			streamtagJson(qw422016, v)
//line jaeger.qtpl:156
		}
//line jaeger.qtpl:157
	}
//line jaeger.qtpl:157
	qw422016.N().S(`],"traceID":`)
//line jaeger.qtpl:159
	qw422016.N().Q(span.traceID)
//line jaeger.qtpl:159
	qw422016.N().S(`,"warnings":null}`)
//line jaeger.qtpl:162
}

//line jaeger.qtpl:162
func writespanJson(qq422016 qtio422016.Writer, span *span) {
//line jaeger.qtpl:162
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jaeger.qtpl:162
	streamspanJson(qw422016, span)
//line jaeger.qtpl:162
	qt422016.ReleaseWriter(qw422016)
//line jaeger.qtpl:162
}

//line jaeger.qtpl:162
func spanJson(span *span) string {
//line jaeger.qtpl:162
	qb422016 := qt422016.AcquireByteBuffer()
//line jaeger.qtpl:162
	writespanJson(qb422016, span)
//line jaeger.qtpl:162
	qs422016 := string(qb422016.B)
//line jaeger.qtpl:162
	qt422016.ReleaseByteBuffer(qb422016)
//line jaeger.qtpl:162
	return qs422016
//line jaeger.qtpl:162
}

//line jaeger.qtpl:164
func streamtagJson(qw422016 *qt422016.Writer, tag keyValue) {
//line jaeger.qtpl:164
	qw422016.N().S(`{"key":`)
//line jaeger.qtpl:166
	qw422016.N().Q(tag.key)
//line jaeger.qtpl:166
	qw422016.N().S(`,"type":"string","value":`)
//line jaeger.qtpl:168
	qw422016.N().Q(tag.vStr)
//line jaeger.qtpl:168
	qw422016.N().S(`}`)
//line jaeger.qtpl:170
}

//line jaeger.qtpl:170
func writetagJson(qq422016 qtio422016.Writer, tag keyValue) {
//line jaeger.qtpl:170
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jaeger.qtpl:170
	streamtagJson(qw422016, tag)
//line jaeger.qtpl:170
	qt422016.ReleaseWriter(qw422016)
//line jaeger.qtpl:170
}

//line jaeger.qtpl:170
func tagJson(tag keyValue) string {
//line jaeger.qtpl:170
	qb422016 := qt422016.AcquireByteBuffer()
//line jaeger.qtpl:170
	writetagJson(qb422016, tag)
//line jaeger.qtpl:170
	qs422016 := string(qb422016.B)
//line jaeger.qtpl:170
	qt422016.ReleaseByteBuffer(qb422016)
//line jaeger.qtpl:170
	return qs422016
//line jaeger.qtpl:170
}

//line jaeger.qtpl:172
func streamlogJson(qw422016 *qt422016.Writer, l log) {
//line jaeger.qtpl:172
	qw422016.N().S(`{"timestamp":`)
//line jaeger.qtpl:174
	qw422016.N().DL(l.timestamp)
//line jaeger.qtpl:174
	qw422016.N().S(`,"fields":[`)
//line jaeger.qtpl:176
	if len(l.fields) > 0 {
//line jaeger.qtpl:177
		streamtagJson(qw422016, l.fields[0])
//line jaeger.qtpl:178
		for _, v := range l.fields[1:] {
//line jaeger.qtpl:178
			qw422016.N().S(`,`)
//line jaeger.qtpl:179
			streamtagJson(qw422016, v)
//line jaeger.qtpl:180
		}
//line jaeger.qtpl:181
	}
//line jaeger.qtpl:181
	qw422016.N().S(`]}`)
//line jaeger.qtpl:184
}

//line jaeger.qtpl:184
func writelogJson(qq422016 qtio422016.Writer, l log) {
//line jaeger.qtpl:184
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jaeger.qtpl:184
	streamlogJson(qw422016, l)
//line jaeger.qtpl:184
	qt422016.ReleaseWriter(qw422016)
//line jaeger.qtpl:184
}

//line jaeger.qtpl:184
func logJson(l log) string {
//line jaeger.qtpl:184
	qb422016 := qt422016.AcquireByteBuffer()
//line jaeger.qtpl:184
	writelogJson(qb422016, l)
//line jaeger.qtpl:184
	qs422016 := string(qb422016.B)
//line jaeger.qtpl:184
	qt422016.ReleaseByteBuffer(qb422016)
//line jaeger.qtpl:184
	return qs422016
//line jaeger.qtpl:184
}

//line jaeger.qtpl:186
func streamspanRefJson(qw422016 *qt422016.Writer, ref spanRef) {
//line jaeger.qtpl:186
	qw422016.N().S(`{"refType":`)
//line jaeger.qtpl:188
	qw422016.N().Q(ref.refType)
//line jaeger.qtpl:188
	qw422016.N().S(`,"spanID":`)
//line jaeger.qtpl:189
	qw422016.N().Q(ref.spanID)
//line jaeger.qtpl:189
	qw422016.N().S(`,"traceID":`)
//line jaeger.qtpl:190
	qw422016.N().Q(ref.traceID)
//line jaeger.qtpl:190
	qw422016.N().S(`}`)
//line jaeger.qtpl:192
}

//line jaeger.qtpl:192
func writespanRefJson(qq422016 qtio422016.Writer, ref spanRef) {
//line jaeger.qtpl:192
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jaeger.qtpl:192
	streamspanRefJson(qw422016, ref)
//line jaeger.qtpl:192
	qt422016.ReleaseWriter(qw422016)
//line jaeger.qtpl:192
}

//line jaeger.qtpl:192
func spanRefJson(ref spanRef) string {
//line jaeger.qtpl:192
	qb422016 := qt422016.AcquireByteBuffer()
//line jaeger.qtpl:192
	writespanRefJson(qb422016, ref)
//line jaeger.qtpl:192
	qs422016 := string(qb422016.B)
//line jaeger.qtpl:192
	qt422016.ReleaseByteBuffer(qb422016)
//line jaeger.qtpl:192
	return qs422016
//line jaeger.qtpl:192
}
