dashboard-copy:

# Copies listed dashboards to vm/* but changes the datasource type from Prometheus to VictoriaMetrics.
# The command should be called before committing changes to dashboards/* files.
dashboards-sync:
