// Code generated by qtc from "traces_json.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:1
package pb

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:1
import (
	"encoding/base64"
	"strconv"
)

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:19
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:19
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:19
func StreamTracesDataJSON(qw422016 *qt422016.Writer, rss []*ResourceSpans) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:19
	qw422016.N().S(`{"resourceSpans":[`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:22
	for i, rs := range rss {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:23
		if i > 0 {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:23
			qw422016.N().S(`,`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:23
		}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:24
		streamresourceSpansJSON(qw422016, rs)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:25
	}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:25
	qw422016.N().S(`]}`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
func WriteTracesDataJSON(qq422016 qtio422016.Writer, rss []*ResourceSpans) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
	StreamTracesDataJSON(qw422016, rss)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
func TracesDataJSON(rss []*ResourceSpans) string {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
	WriteTracesDataJSON(qb422016, rss)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
	qs422016 := string(qb422016.B)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
	return qs422016
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:28
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:30
func streamresourceSpansJSON(qw422016 *qt422016.Writer, rs *ResourceSpans) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:30
	qw422016.N().S(`{"resource":{"attributes":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:33
	streamkeyValuesJSON(qw422016, rs.Resource.Attributes)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:33
	qw422016.N().S(`},"scopeSpans":[`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:36
	for i, ss := range rs.ScopeSpans {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:37
		if i > 0 {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:37
			qw422016.N().S(`,`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:37
		}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:38
		streamscopeSpansJSON(qw422016, ss)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:39
	}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:39
	qw422016.N().S(`],"schemaUrl":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:41
	qw422016.N().Q(rs.SchemaURL)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:41
	qw422016.N().S(`}`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
func writeresourceSpansJSON(qq422016 qtio422016.Writer, rs *ResourceSpans) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
	streamresourceSpansJSON(qw422016, rs)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
func resourceSpansJSON(rs *ResourceSpans) string {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
	writeresourceSpansJSON(qb422016, rs)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
	qs422016 := string(qb422016.B)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
	return qs422016
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:43
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:45
func streamscopeSpansJSON(qw422016 *qt422016.Writer, ss *ScopeSpans) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:45
	qw422016.N().S(`{"scope":{"name":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:48
	qw422016.N().Q(ss.Scope.Name)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:48
	qw422016.N().S(`,"version":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:49
	qw422016.N().Q(ss.Scope.Version)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:49
	qw422016.N().S(`,"attributes":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:50
	streamkeyValuesJSON(qw422016, ss.Scope.Attributes)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:50
	qw422016.N().S(`,"droppedAttributesCount":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:51
	qw422016.N().DUL(uint64(ss.Scope.DroppedAttributesCount))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:51
	qw422016.N().S(`},"spans":[`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:54
	for i, s := range ss.Spans {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:55
		if i > 0 {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:55
			qw422016.N().S(`,`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:55
		}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:56
		streamspanJSON(qw422016, s)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:57
	}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:57
	qw422016.N().S(`],"schemaUrl":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:59
	qw422016.N().Q(ss.SchemaURL)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:59
	qw422016.N().S(`}`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
func writescopeSpansJSON(qq422016 qtio422016.Writer, ss *ScopeSpans) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
	qw422016 := qt422016.AcquireWriter(qq422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
	streamscopeSpansJSON(qw422016, ss)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
	qt422016.ReleaseWriter(qw422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
func scopeSpansJSON(ss *ScopeSpans) string {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
	qb422016 := qt422016.AcquireByteBuffer()
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
	writescopeSpansJSON(qb422016, ss)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
	qs422016 := string(qb422016.B)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
	qt422016.ReleaseByteBuffer(qb422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
	return qs422016
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:61
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:63
func streamspanJSON(qw422016 *qt422016.Writer, s *Span) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:63
	qw422016.N().S(`{"traceId":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:65
	qw422016.N().Q(s.TraceID)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:65
	qw422016.N().S(`,"spanId":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:66
	qw422016.N().Q(s.SpanID)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:66
	qw422016.N().S(`,"traceState":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:67
	qw422016.N().Q(s.TraceState)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:67
	qw422016.N().S(`,"parentSpanId":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:68
	qw422016.N().Q(s.ParentSpanID)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:68
	qw422016.N().S(`,"flags":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:69
	qw422016.N().DUL(uint64(s.Flags))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:69
	qw422016.N().S(`,"name":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:70
	qw422016.N().Q(s.Name)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:70
	qw422016.N().S(`,"kind":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:71
	qw422016.N().D(int(s.Kind))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:71
	qw422016.N().S(`,"startTimeUnixNano":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:72
	qw422016.N().Q(strconv.FormatUint(s.StartTimeUnixNano, 10))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:72
	qw422016.N().S(`,"endTimeUnixNano":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:73
	qw422016.N().Q(strconv.FormatUint(s.EndTimeUnixNano, 10))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:73
	qw422016.N().S(`,"attributes":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:74
	streamkeyValuesJSON(qw422016, s.Attributes)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:74
	qw422016.N().S(`,"droppedAttributesCount":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:75
	qw422016.N().DUL(uint64(s.DroppedAttributesCount))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:75
	qw422016.N().S(`,"events":[`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:77
	for i, e := range s.Events {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:78
		if i > 0 {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:78
			qw422016.N().S(`,`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:78
		}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:79
		streamspanEventJSON(qw422016, e)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:80
	}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:80
	qw422016.N().S(`],"droppedEventsCount":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:82
	qw422016.N().DUL(uint64(s.DroppedEventsCount))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:82
	qw422016.N().S(`,"links":[`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:84
	for i, l := range s.Links {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:85
		if i > 0 {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:85
			qw422016.N().S(`,`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:85
		}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:86
		streamspanLinkJSON(qw422016, l)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:87
	}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:87
	qw422016.N().S(`],"droppedLinksCount":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:89
	qw422016.N().DUL(uint64(s.DroppedLinksCount))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:89
	qw422016.N().S(`,"status":{"message":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:91
	qw422016.N().Q(s.Status.Message)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:91
	qw422016.N().S(`,"code":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:92
	qw422016.N().D(int(s.Status.Code))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:92
	qw422016.N().S(`}}`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
func writespanJSON(qq422016 qtio422016.Writer, s *Span) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
	qw422016 := qt422016.AcquireWriter(qq422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
	streamspanJSON(qw422016, s)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
	qt422016.ReleaseWriter(qw422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
func spanJSON(s *Span) string {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
	qb422016 := qt422016.AcquireByteBuffer()
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
	writespanJSON(qb422016, s)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
	qs422016 := string(qb422016.B)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
	qt422016.ReleaseByteBuffer(qb422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
	return qs422016
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:95
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:97
func streamspanEventJSON(qw422016 *qt422016.Writer, e *SpanEvent) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:97
	qw422016.N().S(`{"timeUnixNano":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:99
	qw422016.N().Q(strconv.FormatUint(e.TimeUnixNano, 10))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:99
	qw422016.N().S(`,"name":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:100
	qw422016.N().Q(e.Name)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:100
	qw422016.N().S(`,"attributes":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:101
	streamkeyValuesJSON(qw422016, e.Attributes)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:101
	qw422016.N().S(`,"droppedAttributesCount":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:102
	qw422016.N().DUL(uint64(e.DroppedAttributesCount))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:102
	qw422016.N().S(`}`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
func writespanEventJSON(qq422016 qtio422016.Writer, e *SpanEvent) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
	qw422016 := qt422016.AcquireWriter(qq422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
	streamspanEventJSON(qw422016, e)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
	qt422016.ReleaseWriter(qw422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
func spanEventJSON(e *SpanEvent) string {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
	qb422016 := qt422016.AcquireByteBuffer()
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
	writespanEventJSON(qb422016, e)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
	qs422016 := string(qb422016.B)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
	qt422016.ReleaseByteBuffer(qb422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
	return qs422016
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:104
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:106
func streamspanLinkJSON(qw422016 *qt422016.Writer, l *SpanLink) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:106
	qw422016.N().S(`{"traceId":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:108
	qw422016.N().Q(l.TraceID)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:108
	qw422016.N().S(`,"spanId":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:109
	qw422016.N().Q(l.SpanID)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:109
	qw422016.N().S(`,"traceState":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:110
	qw422016.N().Q(l.TraceState)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:110
	qw422016.N().S(`,"attributes":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:111
	streamkeyValuesJSON(qw422016, l.Attributes)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:111
	qw422016.N().S(`,"droppedAttributesCount":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:112
	qw422016.N().DUL(uint64(l.DroppedAttributesCount))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:112
	qw422016.N().S(`,"flags":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:113
	qw422016.N().DUL(uint64(l.Flags))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:113
	qw422016.N().S(`}`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
func writespanLinkJSON(qq422016 qtio422016.Writer, l *SpanLink) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
	qw422016 := qt422016.AcquireWriter(qq422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
	streamspanLinkJSON(qw422016, l)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
	qt422016.ReleaseWriter(qw422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
func spanLinkJSON(l *SpanLink) string {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
	qb422016 := qt422016.AcquireByteBuffer()
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
	writespanLinkJSON(qb422016, l)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
	qs422016 := string(qb422016.B)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
	qt422016.ReleaseByteBuffer(qb422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
	return qs422016
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:115
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:117
func streamkeyValuesJSON(qw422016 *qt422016.Writer, kvs []*KeyValue) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:117
	qw422016.N().S(`[`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:119
	for i, kv := range kvs {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:120
		if i > 0 {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:120
			qw422016.N().S(`,`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:120
		}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:120
		qw422016.N().S(`{"key":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:122
		qw422016.N().Q(kv.Key)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:122
		qw422016.N().S(`,"value":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:123
		streamanyValueJSON(qw422016, kv.Value)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:123
		qw422016.N().S(`}`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:125
	}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:125
	qw422016.N().S(`]`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
func writekeyValuesJSON(qq422016 qtio422016.Writer, kvs []*KeyValue) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
	qw422016 := qt422016.AcquireWriter(qq422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
	streamkeyValuesJSON(qw422016, kvs)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
	qt422016.ReleaseWriter(qw422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
func keyValuesJSON(kvs []*KeyValue) string {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
	qb422016 := qt422016.AcquireByteBuffer()
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
	writekeyValuesJSON(qb422016, kvs)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
	qs422016 := string(qb422016.B)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
	qt422016.ReleaseByteBuffer(qb422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
	return qs422016
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:127
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:133
func streamanyValueJSON(qw422016 *qt422016.Writer, av *AnyValue) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:134
	if av == nil {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:134
		qw422016.N().S(`{}`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:136
		return
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:137
	}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:137
	qw422016.N().S(`{`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:139
	switch {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:140
	case av.StringValue != nil:
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:140
		qw422016.N().S(`"stringValue":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:141
		qw422016.N().Q(*av.StringValue)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:142
	case av.BoolValue != nil:
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:142
		qw422016.N().S(`"boolValue":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:143
		qw422016.N().V(*av.BoolValue)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:144
	case av.IntValue != nil:
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:144
		qw422016.N().S(`"intValue":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:145
		qw422016.N().Q(strconv.FormatInt(*av.IntValue, 10))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:146
	case av.DoubleValue != nil:
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:146
		qw422016.N().S(`"doubleValue":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:147
		qw422016.N().S(float64AsString(*av.DoubleValue))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:148
	case av.BytesValue != nil:
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:148
		qw422016.N().S(`"bytesValue":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:149
		qw422016.N().Q(base64.StdEncoding.EncodeToString(*av.BytesValue))
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:150
	case av.ArrayValue != nil:
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:150
		qw422016.N().S(`"arrayValue":{"values":[`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:153
		for i, v := range av.ArrayValue.Values {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:154
			if i > 0 {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:154
				qw422016.N().S(`,`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:154
			}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:155
			streamanyValueJSON(qw422016, v)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:156
		}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:156
		qw422016.N().S(`]}`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:159
	case av.KeyValueList != nil:
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:159
		qw422016.N().S(`"kvlistValue":{"values":`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:161
		streamkeyValuesJSON(qw422016, av.KeyValueList.Values)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:161
		qw422016.N().S(`}`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:163
	}
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:163
	qw422016.N().S(`}`)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
func writeanyValueJSON(qq422016 qtio422016.Writer, av *AnyValue) {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
	qw422016 := qt422016.AcquireWriter(qq422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
	streamanyValueJSON(qw422016, av)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
	qt422016.ReleaseWriter(qw422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
}

//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
func anyValueJSON(av *AnyValue) string {
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
	qb422016 := qt422016.AcquireByteBuffer()
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
	writeanyValueJSON(qb422016, av)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
	qs422016 := string(qb422016.B)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
	qt422016.ReleaseByteBuffer(qb422016)
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
	return qs422016
//line lib/protoparser/opentelemetry/pb/traces_json.qtpl:165
}
