name: build

on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - '**/Dockerfile'
      - '**/Makefile'
      - '!app/vmui/Makefile'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.go'
      - '**/Dockerfile'
      - '**/Makefile'
      - '!app/vmui/Makefile'
      - '.github/workflows/build.yml'

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    name: Build
    # Runs on dedicated runner with extra resources to increase build speed.
    runs-on: 'vm-runner'
    steps:
      - name: Code checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3

      - name: Setup Go
        id: go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false

      - name: Cache Go artifacts
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
        with:
          path: |
            ~/.cache/go-build
            ~/go/bin
            ~/go/pkg/mod
          key: go-artifacts-${{ runner.os }}-crossbuild-${{ steps.go.outputs.go-version }}-${{ hashFiles('go.sum', 'Makefile', 'app/**/Makefile') }}
          restore-keys: go-artifacts-${{ runner.os }}-crossbuild-

      - name: Run crossbuild
        run: make crossbuild
